### ISSUE TITLE
Duplication of concerns with control repo modules best practices 

### ISSUE THREAD

**Issue by jessereynolds** [puppetlabs/best-practices#11]
The following two best practice docs both touch on whether (and when) component modules should be included in the site dir of a control repo. They have subtly different things to say:

- https://github.com/puppetlabs/best-practices/blob/master/control-repo-contents.md#component-modules
- https://github.com/puppetlabs/best-practices/blob/master/puppet-modules-and-the-control-repo.md#preferred-option

We should work out whether we need both of these documents - perhaps we can merge them? Alternatively, their boundaries need to be more closely defined.

**Comment by ghost** [comment]
Rando here.  I agree because in reading the first doc the control repo conceptual framework immediately started coming to mind and I found myself getting confused about environment vs control-repo etc.

**Comment by davidsandilands** [comment]
Closing as these documents will get no further updates and any kept information will be transferred  and refactored into patterns and tactics
