### ISSUE TITLE
Environment definition too vague

### ISSUE THREAD

**Issue by ghost** [puppetlabs/best-practices#17]
https://github.com/puppetlabs/best-practices/blob/9dab8034b10c52ea2156391a8cf1ba4d6aa5905f/use-of-environment-in-hiera-hierarchy.md defines a puppet environment as, "A directory on the master containing Puppet code."  That means that ../my_mod/manifests and ../my_mod/manifests/other_puppet_code are separate environments and clearly that isn't what was desired.  If I am missing something I'd like to know what simply for the purposes of educating myself.  Otherwise maybe the definition could be made more specific.

**Comment by suhailc** [comment]
Hi,

But actually you can specify any directory in the hierarchy.yaml so it is
correct that it is not more specific. Of course it is assumed that the
reader is familiar enough with puppet to know that the manifests folder is
not what you specify in hierarchy.yaml

Regards,
Suhail.

**Comment by ghost** [comment]
Okay.  I figured that the definition was being used more in the context of newer Puppet which presumes the use of Hiera.  Thanks.
