### ISSUE TITLE
different `moduledir` documentation

### ISSUE THREAD

**Issue by crazymind1337** [puppetlabs/best-practices#19]
The best practice text (1) says the method of using `moduledir` is undocumented but I can find a documentation at the puppetlabs/r10k (2) repository.

I am now a bit confused, because for me it is very handy to define a `moduledir` within the `Puppetfile`.

(1) https://github.com/puppetlabs/best-practices/blob/master/separate-hieradata-repository.md#moduledir-method-in-r10k-140-it-became-possible-to-use-the-moduledir 

(2) https://github.com/puppetlabs/r10k/blob/master/doc/puppetfile.mkd#moduledir

**Comment by npwalker** [comment]
@crazymind1337 I believe the best-practice is saying you shouldn't use the `moduledir` to achieve what `install_path` does.  The `moduledir` documentation does not mention anything about using it to place a hieradata repo outside of the modules directory.  

If you're using `moduledir` for something other than moving where your hieradata is placed on disk then I think you're fine.  

Does that make sense?

**Comment by crazymind1337** [comment]
Ah okay. I understand now - thanks.

**Comment by baurmatt** [comment]
@npwalker Could you please make this a little bit clearer in https://github.com/puppetlabs/best-practices/blob/master/separate-hieradata-repository.md#moduledir-method-in-r10k-140-it-became-possible-to-use-the-moduledir? I didn't interpreted that text as "`moduledir` shouldn't be used with hieradata" but "`moduledir` should never be used - use `install_path`".

Thanks!

**Comment by npwalker** [comment]
@baurmatt Do you have any suggestions on how to make it clearer?  It seems clear to me but I helped write this so I'm biased.

**Comment by baurmatt** [comment]
@npwalker Sure! :) I've open up #20 in which I try to clarify the wording (at least in my head) so that no one else gets confused. Hope that's alright.
